name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente (dev/prod)'
        required: true
        type: choice
        options:
          - dev
          - prod
      tech:
        description: 'Escolha a stack (Python, Node.js, etc.)'
        required: true
        type: choice
        options:
          - python3.9
          - nodejs18.x

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório `terraform-infra`
        uses: actions/checkout@v3

      - name: Checkout código do repositório `lambda-code`
        uses: actions/checkout@v3
        with:
          repository: ludicsa/lambda-code  
          path: lambda-code
          ref: master

      - name: Gerar ZIP do código da Lambda
        run: |
          cd lambda-code/src
          zip -r lambda.zip .

      - name: Verificar se o ZIP foi criado
        run: ls -lh lambda-code/src/lambda.zip

      - name: Criar diretório do Terraform e mover ZIP
        run: |
          mkdir -p terraform-infra
          mv lambda-code/src/lambda.zip terraform-infra/lambda.zip

      - name: Definir caminho do ZIP da Lambda
        run: echo "LAMBDA_ZIP_PATH=terraform-infra/lambda.zip" >> $GITHUB_ENV

      - name: Configurar AWS Credenciais
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Limpar Cache do Terraform
        run: rm -rf .terraform

      - name: Inicializar Terraform
        run: |
          terraform init \
            -backend-config="bucket=terraform-tfstate-87879564" \
            -backend-config="key=infra/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Criar Plano do Terraform
        run: |
          terraform plan -out=tfplan \
            -var="environment=${{ github.event.inputs.environment }}" \
            -var="lambda_zip_path=${{ env.LAMBDA_ZIP_PATH }}" \
            -var="tech=${{ github.event.inputs.tech }}"
            -var="runtime=${{ github.event.inputs.tech }}"
      
      - name: Aplicar Terraform
        run: terraform apply -auto-approve tfplan
