name: Deploy Lambda with Terraform

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Linguagem da Lambda (ex: python3.9, nodejs18.x)'
        required: true
      env:
        description: 'Ambiente de destino (dev ou prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório Terraform
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', inputs.env)] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', inputs.env)] }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          echo "Usando ambiente: ${{ inputs.env }}"

      - name: Clonar código da Lambda
        uses: actions/checkout@v4
        with:
          repository: 'ludicsa/lambda-code'
          path: 'lambda-code'

      - name: Compactar código da Lambda
        run: |
          cd lambda-code/src
          zip -r ../../lambda.zip .

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Aplicar Terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var "lambda_runtime=${{ inputs.runtime }}" \
            -var "lambda_zip_file=lambda.zip"
